language: erlang
otp_release:
    - 17.1
before_install:
    - wget https://github.com/elixir-lang/elixir/releases/download/v1.0.0/Precompiled.zip -O elixir.zip
    - unzip -d elixir elixir.zip
    - export PATH=$(pwd)/elixir/bin:$PATH
    - epmd -daemon
    - mix local.hex
script:
    - mix test --exclude distributed:true
notifications:
    recipients:
        - james@fishcakez.com

